### ISSUE TITLE
Updating CRoaring to latest version (0.2.4)

### ISSUE THREAD

**Issue by lemire** [RogueException/CRoaring.Net#1]
Consider updating to the latest version.

**Comment by lemire** [comment]
Latest version exposes the CRoaring version, which is handy... https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring_version.h

**Comment by lemire** [comment]
There is also a function to add a bunch of integers quickly...

```
 void roaring_bitmap_add_many(roaring_bitmap_t * r, size_t n_args, const uint32_t *vals);
```

**Comment by phnx47** [comment]
I upgrade CRoaring to v0.2.18: https://github.com/RogueException/CRoaring.Net/pull/2

**Comment by RogueException** [comment]
Updated to 0.2.22 in https://github.com/RogueException/CRoaring.Net/commit/b7e362f6a5b69a2ef5444189b8e59b7ec5fce5a3
