### ISSUE TITLE
Add AndCardinality

### ISSUE THREAD

**Issue by eladmarg** [RogueException/CRoaring.Net#3]
Hi,

Any chance to add [andCardinality](http://lemire.me/docs/RoaringBitmap/org/roaringbitmap/RoaringBitmap.html#andCardinality-org.roaringbitmap.RoaringBitmap-org.roaringbitmap.RoaringBitmap-) ?

**Comment by lemire** [comment]
Ties in with this issue https://github.com/RoaringBitmap/CRoaring/issues/67

**Comment by lemire** [comment]
@RogueException @eladmarg   I suggest to unblock this. The current release of CRoaring supports and_cardinality, or_cardinality, intersect, xor_cardinality, andnot_cardinality, jaccard_index...  Given that CRoaring has these functions now, I suppose it is trivial to expose them to C#.

**Comment by RogueException** [comment]
This is ready as soon as https://github.com/RoaringBitmap/CRoaring/pull/93 is accepted

**Comment by RogueException** [comment]
Added in https://github.com/RogueException/CRoaring.Net/commit/40935233157b3477dd7f6d734a4bf02884c8ee8b
