### ISSUE TITLE
Upgrade to CRoaring 0.2.15

### ISSUE THREAD

**Issue by lemire** [RogueException/CRoaring.Net#4]
https://github.com/RoaringBitmap/CRoaring/releases/tag/v0.2.15

Pregenerated unity builds...

https://github.com/lemire/CRoaringUnityBuild

**Comment by lemire** [comment]
With latest CRoaring, we have iterators that could be useful...

```
roaring_uint32_iterator_t *  i = roaring_create_iterator(r1);
while(i->has_value) {
   //use: i->current_value
   roaring_advance_uint32_iterator(i);
}
roaring_free_uint32_iterator(i);
```

**Comment by lemire** [comment]
We also now have maximum/minimum and rank functions.

**Comment by phnx47** [comment]
I upgrade CRoaring to v0.2.18: https://github.com/RogueException/CRoaring.Net/pull/2

**Comment by RogueException** [comment]
Updated to 0.2.22 in https://github.com/RogueException/CRoaring.Net/commit/b7e362f6a5b69a2ef5444189b8e59b7ec5fce5a3
